version: "3.7"

services:

  parse_insert:
    build: ./flow
    command: python3 /usr/app/parse_insert.py
    volumes:
      - "./flow/parse_insert.py:/usr/app/parse_insert.py:ro"
      - type: bind
        source: ./flow/config.toml
        target: /root/.prefect/config.toml
        read_only: true
    env_file:
      - .env
    environment:
      MINIO_SCHEME: ${MINIO_SCHEME}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MAX_ES_ROW_INJECT: ${MAX_ES_ROW_INJECT}
      ELASTIC_SCHEME: ${ELASTIC_SCHEME}
      ELASTIC_PORT: ${ELASTIC_PORT}
      ELASTIC_ENDPOINT: ${ELASTIC_ENDPOINT}
      ELASTIC_USER: ${ELASTIC_USER}
      ELASTIC_PWD: ${ELASTICSEARCH_PWD}