version: "3.7"

services:

    weather:
        build: .
        command: python3 /usr/app/weather.py
        volumes:
            - type: bind
              source: ./weather.py
              target: /usr/app/weather.py
              read_only: true
            - type: bind
              source: ./s3_utils.py
              target: /usr/app/s3_utils.py
              read_only: true
            - type: bind
              source: ./config.toml
              target: /root/.prefect/config.toml
              read_only: true
        depends_on:
            - minio
