version: "3.7"

services:

  searchkit:
    build: ./
    environment:
      ELASTIC_SCHEME: ${ELASTIC_SCHEME}
      ELASTIC_PORT: ${ELASTIC_PORT}
      ELASTIC_ENDPOINT: ${ELASTIC_ENDPOINT}
      ELASTIC_USER: ${ELASTICSEARCH_USER}
      ELASTIC_PWD: ${ELASTICSEARCH_PWD}
    ports:
        - 3000:3000
